# Generated by Django 4.2.11 on 2025-03-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Cash Account', 'Cash Accounts'), ('Credit Accounts', 'Credit Accounts'), ('Mortgages and Loans', 'Mortgages And Loans'), ('Tracking Accounts', 'Tracking Accounts')], default='Cash Account', max_length=20),
        ),
    ]
