# Generated by Django 4.2.11 on 2025-03-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
        migrations.AddField(
            model_name='account',
            name='kind',
            field=models.CharField(choices=[('Checking', 'Checking'), ('Savings', 'Savings'), ('Asset', 'Asset')], default='Checking', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.category'),
        ),
    ]
