# Generated by Django 5.1.7 on 2025-04-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_transaction_inflow_alter_transaction_memo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='inflow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='outflow',
            field=models.IntegerField(default=0),
        ),
    ]
